schema: "classroom50/repo-config/v1"
classroom: "cbnu-soft-eng"
assignment: "software-engineering-project"
owner:
  username: "trivonce"
  id: 85108522
  accepted_at: "2026-09-10T08:03:34Z"
source:
  owner: "aaronkr-2026-2"
  owner_id: 314234319
  repo: "software-project"
  branch: "main"
